[build]
command = "npm run build"
functions = "netlify/functions/"
publish = "build/"
base = "webapp/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 9000

[functions]
  external_node_modules = ["@prisma/client"]