[build]
command = "cd webapp && npm run build"
functions = "netlify/functions/"
publish = "build/"
base = "webapp/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 9000
